FROM alpine:3.12.0

RUN apk add --no-cache --update \
		bash \
		conntrack-tools \
		coreutils \
		curl \
		drill \
		iperf3 \
		iproute2 \
		iptables \
		iputils \
		ip6tables \
		keepalived \
		net-tools \
		nftables \
		socat \
		ethtool \
		mtr \
		tcpdump \
		bind \
		busybox-extras

ADD helloworld /app/bin/
ADD start.sh /app/bin/
ADD stop.sh /app/bin/
ADD restart.sh /app/bin/

WORKDIR /app

ENTRYPOINT ["bin/start.sh"]
