FROM alpine:3.12.0

RUN apk add --no-cache --update \
		bash \
		conntrack-tools \
		coreutils \
		curl \
		drill \
		iperf3 \
		iproute2 \
		iptables \
		iputils \
		ip6tables \
		keepalived \
		net-tools \
		nftables \
		socat \
		ethtool \
		mtr \
		tcpdump \
		bind \
		busybox-extras

ADD helloworld helloworld

ENTRYPOINT ["/helloworld"]
